### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ikhoon**
- Armeria 1.18.0 -> 1.19.0
- Jackson 2.13.3 -> 2.13.4
- javassist 3.29.0 -> 3.29.1
- Micrometer 1.9.2 -> 1.9.3
- Spring Boot 2.7.2 -> 2.7.3
- Build
  - Checkstyle 10.3.2 -> 10.3.3
  - jmh-gradle-plugin 0.6.6 -> 0.6.7
  - Mocktio 4.6.1 -> 4.8.0

### CODE REVIEW

**Comment by minwoox** [comment]
Could you add `CentralDogmaEndpointGroup.toString()` using `DynamicEndpointGroup.toStringHelper()`, please? 😄

**Comment by ikhoon** [comment]
> Could you add `CentralDogmaEndpointGroup.toString()` using `DynamicEndpointGroup.toStringHelper()`, please? 😄

For sure. Nice catch!

**Review by jrhee17 — APPROVED** [review]
Thanks @ikhoon ! 🙇 👍 🙇

**Review by minwoox — APPROVED** [review]
Thanks! 😄

**Comment by ikhoon** [comment]
Thanks for the quick review! 🙇‍♂️

**Pull request merged**
