### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ikhoon**
- Armeria 1.7.2 -> 1.8.0
- Caffeine 2.9.0 -> 2.9.1
- jcommander 1.78 -> 1.81
- JGit 5.11.0 -> 5.11.1
- Micrometer 1.6.6 -> 1.7.0
- Mocktio 3.9.0 -> 3.10.0
- Build
  - awaitility 4.0.3 -> 4.1.0
  - gradle-docker-plugin 6.7.0 -> 7.0.0
  - jmh-gradle-plugin 0.5.3 -> 0.6.4
  - jmh 1.29 -> 1.31
  - JUnit 5.7.1 -> 5.7.2
  - NodeJS 10.19.0 -> 16.1.0
  - Yarn 1.17.3 -> 1.22.10

### CODE REVIEW

**Comment by minwoox** [comment]
https://github.com/line/centraldogma/pull/598/checks?check_run_id=2618790596#step:6:209
Oops, could you check the failure, please?

**Comment by ikhoon** [comment]
> [#598 (checks)](https://github.com/line/centraldogma/pull/598/checks?check_run_id=2618790596#step:6:209)
> Oops, could you check the failure, please?

Yeah, I need to revert it. 😅

**Comment by ikhoon** [comment]
PTAL. 🙇‍♂️

**Review by minwoox — APPROVED** [review]
Thanks a lot!

**Pull request merged**
