### PR TITLE
Add a path from a project page to a metadata page on UI

### PR DESCRIPTION
**Pull request by hokkun-dayo**
It seems nice in practice to me if there is a path from a project page (`#/projects/xxx`) to a metadata page (`#/metadata/xxx`) on the UI.

Here is a screenshot:
Screen Shot 2021-06-04 at 15 45 49

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Looking good! Thanks, @hokkun-dayo.

**Comment by trustin** [comment]
Should we move the button down so all buttons are grouped together?

**Comment by minwoox** [comment]
Can we also remove the `meta` repository from the list? 🤔

**Comment by hokkun-dayo** [comment]
@trustin 
> Should we move the button down so all buttons are grouped together? Or perhaps we could move the Create a repository button up. 😄

Sure, I'll try it.

**Comment by hokkun-dayo** [comment]
@minwoox 
IIUC, contents in `meta` directory and what we can see in `#/metadata/xxx` are different, so it seems that we don't have to remove that. Any thoughts?

**Comment by hokkun-dayo** [comment]
Modified one
Screen Shot 2021-06-10 at 18 20 14

**Comment by minwoox** [comment]
> @minwoox
IIUC, contents in meta directory and what we can see in #/metadata/xxx are different, so it seems that we don't have to remove that. Any thoughts?

Yes, exactly. Sorry about the comment. 😅

**Review by minwoox — APPROVED** [review]

**Comment by minwoox** [comment]
Thanks @hokkun-dayo!

**Pull request merged**
