### PR TITLE
Refactor http method string to constant in go code

### PR DESCRIPTION
**Pull request by kkamdooong**
Modifications:
* Change to use a constant that exists in the official library instead of string value

### CODE REVIEW

**Comment by trustin** [comment]
Thanks for your first-time pull request! Could you sign the ICLA first? https://feedback.line.me/enquete/public/799-Z6ygVz3U

**Comment by kkamdooong** [comment]
I agreed. 😄

**Comment by trustin** [comment]
@kkamdooong You have to enter your 'mailing address', not your e-mail address. Could you sign again?

**Comment by kkamdooong** [comment]
@trustin Oh..I'm sorry. I fixed that.

**Comment by trustin** [comment]
ICLA confirmed.

**Comment by minwoox** [comment]
Thank you for your first PR!

**Pull request merged**
