### PR TITLE
Remove `:server-auth:webapp`

### PR DESCRIPTION
**Pull request by ikhoon**
Motivation:

CI fails to install Node.js binary for `:server-auth:webapp`. https://github.com/line/centraldogma/actions/runs/10036375065/job/27734008120?pr=989#step:6:163 In fact, the login page is supported by the new webapp so `:server-auth:webapp` is no longer used even for the legacy webapp.

I think the straightforward solution for the CI problem is to remove `:server-auth:webapp`.

Modifications:

- Remove `:server-auth:webapp` and related Gradle tasks.

Result:

Fix CI build failures.

### CODE REVIEW

**Review by minwoox — APPROVED** [review]
👍 👍 👍

**Comment by minwoox** [comment]
Looks like it still fails. 🤔 
https://github.com/line/centraldogma/actions/runs/10051604317/job/27781470253?pr=992#step:6:159

**Comment by ikhoon** [comment]
Deleted Gradle caches and triggered builds 
```
gh cache list |grep gradle | awk '{ print $1 }' | xargs -I {} gh cache delete {} 
```

**Comment by ikhoon** [comment]
Let me merge this PR and make CI work.

**Comment by minwoox** [comment]
@ikhoon 
Could you also check this failure? It faied to merge to main branch.
https://github.com/line/centraldogma/actions/runs/10053176511

**Pull request merged**
