### PR TITLE
Update basic setup with nextjs

### PR DESCRIPTION
**Pull request by rainy789**
Motivation

Add nextjs https://nextjs.org/ considering it has the following pros

- reusable components
- client side routing supported out of the box
- less configuration needed
- automatic code splitting using turbopack (the rust version of webpack) https://nextjs.org/docs/advanced-features/turbopack
- fast refresh (rust-based compiler)
- automatic build size optimisation 
- prerendering 
- overall better developer experience

Modification

- Add nextjs
- Remove webpack
- Replace src/* with pages/*

Result

We can get the same UI with faster refresh plus the other advantages (mentioned above).

### CODE REVIEW

**Comment by ikhoon** [comment]
The minimized bundle size of the base setup with React, NextJs and ChakraUI is 1.26 MB without compression and 158.33 KB with gzip compression.
image
image

**Comment by ikhoon** [comment]
#740 has been merged. Would you mind merging the upstream branch and migrating the new files to use Next.js API?

**Comment by rainy789** [comment]
> #740 has been merged. Would you mind merging the upstream branch and migrating the new files to use Next.js API?

Sorry somehow the PR got closed when I tried syncing the fork with the upstream. 
https://github.com/line/centraldogma/commit/5897f460d13517d9e70ff0dffcd48f1e4e142123#diff-96987cc47fbcd9eef554bfca963267ccb17ed6179c6c72d84d57833c8374caef
Will create a new PR instead.

**Comment by ikhoon** [comment]
>  Will create a new PR instead.

OK. No worries. 😀

**Pull request closed without merging**
