### PR TITLE
Enlarge watcher timeout to give a user more chance to retry

### PR DESCRIPTION
**Pull request by imasahiro**

### CODE REVIEW

**Comment by imasahiro** [comment]
cc: @jongyeol

**Comment by trustin** [comment]
@imasahiro It seems like the new test case is flaky. Could you check the failure at AppVeyor?

**Comment by trustin** [comment]
Still failing unfortunately:

```
com.linecorp.centraldogma.it.CentralDogmaEndpointGroupTest > recoverFromNotFound FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <false>
    to be equal to:
     <true>
    but was not.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.linecorp.centraldogma.it.CentralDogmaEndpointGroupTest.recoverFromNotFound(CentralDogmaEndpointGroupTest.java:132)
```

**Comment by imasahiro** [comment]
yeah.. still finding a way to resolve this flakiness.

**Comment by imasahiro** [comment]
I changed my mind and removed watcher timeout from `CentralDogmaEndpointGroup` because with this blocking, it may blocks other EndpointGroup creation.

**Comment by trustin** [comment]
@minwoox Interested in reviewing?

**Comment by trustin** [comment]
Updated the pull request description.

**Comment by trustin** [comment]
Thanks, @imasahiro !

**Pull request merged**
