### PR TITLE
Replace some usages of TemporaryFolderExtension

### PR DESCRIPTION
**Pull request by KarboniteKream**
#### Motivation
- Try to use `@TempDir` in some tests to see if file deletion logic on Windows has been improved

#### Modifications
- Replace some usages of `TemporaryFolderExtension` with JUnit's `@TempDir`

### CODE REVIEW

**Comment by KarboniteKream** [comment]
Remaining usages of `TemporaryFolderExtension`:

- `PermissionTest` can be made to work locally on Windows, but fails on CI
- `GitMirrorTest` has an issue with `remoteToLocal_submodule()`. Even after closing all repositories, JGit states there's 0 references, but the `.pack` file referencing the submodule cannot be deleted
- `ReplicationWriteQuotaTest` and `ReplicatedLoginAndLogoutTest` have a similar problem. Looks like some file locks remain, even after shutting down replicas.

Looks like the timing of `@TempDir` is different to the extension I implemented. I don't completely understand why it works better. Looks like the tests have much more time to cleanup and release file locks before the extension cleanup runs.

I was hoping to be able to completely remove `TemporaryFolderExtension`, but no such luck 😭

**Review by trustin — APPROVED** [review]
Thanks a lot! What stopped you from replacing 'all' usages?

**Comment by KarboniteKream** [comment]
> What stopped you from replacing 'all' usages?

I explained it in [this comment](https://github.com/line/centraldogma/pull/591#issuecomment-826299414). There seems to be some timing/file lock issues on Windows, which I couldn't completely figure out. Even after stopping the services that seems to keep file locks, `@TempDir` seems to be unable to delete the files.

Please let me know if you have any ideas 🙇

**Review by ikhoon — APPROVED** [review]
Thanks! @KarboniteKream

**Review by minwoox — APPROVED** [review]
>  but no such luck 😭

😭 
Thanks a lot for your effort on this. 😄  I think we can keep using `TemporaryFolderExtension` for the rest of them.

**Comment by ikhoon** [comment]
Thanks again @KarboniteKream

**Pull request merged**
