### PR TITLE
Update Armeria version to 1.27.2

### PR DESCRIPTION
**Pull request by armerian**

### CODE REVIEW

**Comment by ikhoon** [comment]
```
A problem occurred configuring project ':testing:testing-common'.
> Could not resolve all files for configuration ':common:shadedJarTestRuntime'.
   > Could not find com.linecorp.armeria:armeria-thrift0.9:1.27.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/linecorp/armeria/armeria-thrift0.9/1.27.2/armeria-thrift0.9-1.27.2.pom
```
https://repo.maven.apache.org/maven2/com/linecorp/armeria/armeria-bom/1.27.2/armeria-bom-1.27.2.pom
https://repo.maven.apache.org/maven2/com/linecorp/armeria/armeria-thrift0.9/1.27.2/armeria-thrift0.9-1.27.2.pom

**Comment by jrhee17** [comment]
> armeria-bom was published but armeria-thrift0.9 hasn't been published yet. 😅

I guess just listing all Armeria versions we depend on makes sense (since the list doesn't change very often)

**Review by jrhee17 — APPROVED** [review]
🏎️ 🏎️ 🏎️

**Comment by ikhoon** [comment]
> I guess just listing all Armeria versions we depend on makes sense

Good idea. Let me send a fix PR before the next release.

**Pull request merged**
