### PR TITLE
Add missing package-info.java

### PR DESCRIPTION
**Pull request by minwoox**
Motivation:
So that IDE does not complain about nullabilty anymore.

Modifications:
- Add missing package-info.java files
- Add `ElementType.TYPE_USE` to `NonNullByDefault`
  - Related https://github.com/line/armeria/pull/3558

Result:
- Cleanup

### CODE REVIEW

**Review by ikhoon — APPROVED** [review]
Thanks! @minwoox

**Comment by minwoox** [comment]
Thanks!

**Comment by trustin** [comment]
Can we automate this, like adding a Checkstyle rule that errors when `package-info.java` is missing?

**Comment by minwoox** [comment]
> Can we automate this, like adding a Checkstyle rule that errors when package-info.java is missing?

That's a good suggestion. Let me add it. 😉

**Pull request merged**
